import argparse
import os
import sys

import esm
import torch

from lm_design import SimultaneousEsmRecoder, AutoregressiveEsmRecoder, \
    GibbsEsmRecoder, SimultaneousMsaTransRecoder, AutoregressiveMsaTransRecoder 
from utils import save_designs_to_fasta, check_recoded_sequences


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Apply design strategies to recode wild-type genes using protein language models."
    )

    parser.add_argument(
        "--gpu",
        type=int,
        default=0,
        help="Index of GPU to use for computation.",
    )

    # Input/Output
    parser.add_argument(
        "--infile",
        type=str,
        required=True,
        default="data/designs/esm2_3d_neighbors/from_best_designs.fasta",
        help="Path to the input FASTA file containing wild-type sequences."
    )

    parser.add_argument(
        "--outfile",
        type=str,
        required=True,
        default="data/designs/esm2_3d_neighbors/from_best_designs_EAI_3dN_3_5.fasta",
        help="Path to the output FASTA file where recoded sequences will be saved."
    )

    # Recoding parameters
    parser.add_argument(
        "--residue",
        type=str,
        default='I',
        choices=['I', 'V'],
        help="Residue to recode (e.g., 'I' for isoleucine, 'V' for valine)."
    )

    parser.add_argument(
        "--model",
        type=str,
        required=True,
        choices=['esm2', 'msa_trans'],
        help="Pretrained model to use for recoding the wild-type genes. "
            "'esm2' (ESM-2) is a single-sequence protein language model, "
            "while 'msa_trans' (MSA Transformer) requires multiple sequence alignments."
    )

    parser.add_argument(
    "--scheme",
    type=str,
    required=True,
    choices=['simultaneous', 'autoregressive', 'gibbs'],
    help="Design strategy used to recode the wild-type genes. "
         "'simultaneous' modifies all positions at once, 'autoregressive' modifies sequentially, and "
         "'gibbs' iteratively refines the sequence."
    )

    # Input data directories
    parser.add_argument(
        "--msa_dir",
        type=str,
        default=None,
        help="Directory containing multiple sequence alignments (MSAs) of wild-type genes. "
            "Required when using the 'msa_trans' model."
    )

    parser.add_argument(
        "--structure_dir", 
        type=str,
        default=None,
        help="Directory containing PDB structures of wild-type genes. "
            "Required when using spatial neighbors for recoding."
    )

    # Masking strategies
    parser.add_argument(
        "--seq_neighbors",
        action="store_true",
        default=False,
        help="If set, recodes residues adjacent to the target residue in the sequence."
    )

    parser.add_argument(
        "--spatial_neighbors",
        action="store_true",
        default=False,
        help="If set, recodes residues that are spatially close to the target residue in the PDB structure."
    )

    parser.add_argument(
        "--evo_neighbors", 
        action="store_true",
        default=False,
        help="If set, recodes residues that show evolutionary covariance with the target residue."
    )

    # 3D distance thresholds
    parser.add_argument(
        "--min_3d_dist",
        type=float,
        default=3.0,
        help="Minimum spatial distance (in Angstroms) to define 3D neighbors."
    )

    parser.add_argument(
        "--max_3d_dist",
        type=float,
        default=4.0,
        help="Maximum spatial distance (in Angstroms) to define 3D neighbors."
    )

    # Mutation tracking
    parser.add_argument(
        "--save_muts",
        action="store_true",
        default=True,
        help="If set, saves the amino acid replacements generated by the design method."
    )

    parser.add_argument(
        "--use_prev_muts",
        action="store_true",
        default=False,
        help="If set, uses mutations found in a previous design as a starting point to generate new ones."
    )


    args = parser.parse_args()

    if os.path.exists(args.outfile):
        print(f"The file '{args.outfile}' exists.")
        sys.exit(0) 

    if (args.scheme == "gibbs") and (args.spatial_neighbors):
        raise NotImplementedError

    device = f"cuda:{args.gpu}" if torch.cuda.is_available() else "cpu"
    print(f"Model on {device}")

    scheme_to_decoder = {
        'esm2_simultaneous': SimultaneousEsmRecoder,
        'esm2_autoregressive': AutoregressiveEsmRecoder, #MaxLogLikelihoodEsmRecoder,
        'esm2_gibbs': GibbsEsmRecoder,
        'msa_trans_simultaneous': SimultaneousMsaTransRecoder,
        'msa_trans_autoregressive': AutoregressiveMsaTransRecoder, # MaxLogLikelihoodMsaTransRecoder,
    }
    try:
        recoder = scheme_to_decoder[f'{args.model}_{args.scheme}']
        print(recoder)
    except KeyError:
        print(f"Scheme {args.scheme} not implemented for {args.model}.")
    if args.model == 'esm2':
        model, alphabet = esm.pretrained.esm2_t33_650M_UR50D()
    elif args.model == 'msa_trans':
        model, alphabet = esm.pretrained.esm_msa1b_t12_100M_UR50S()

    design_method = recoder(
        seq_file=args.infile,
        msa_dir=args.msa_dir,
        structure_dir=args.structure_dir,
        residue_to_recode=args.residue, 
        model=model, 
        alphabet=alphabet, 
        device=device, 
        incl_seq_neighbors=args.seq_neighbors, 
        incl_3d_neighbors=args.spatial_neighbors, 
        incl_evo_neighbors=args.evo_neighbors,
        min_3d_dist=args.min_3d_dist,
        max_3d_dist=args.max_3d_dist,
        save_muts = args.save_muts
        )

    if args.model == 'esm2':
        designs = design_method.recode()
    elif args.model == 'msa_trans':
        designs = design_method.recode()

    check_recoded_sequences(designs=designs, residue=args.residue)
    save_designs_to_fasta(designs=designs, outpath=args.outfile)



